<a href="https://colab.research.google.com/github/Lee-Gunju/AI-paper-code-review-for-personal-project/blob/master/Endpoint_layer_pattern.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [ ]:
tf.nn.sigmoid
keras.losses.MeanSquaredError
keras.metrics.MeanSquaredError()
keras.losses.SparseCategoricalCrossentropy()

In [ ]:
class LogisticEndpoint(keras.layers.Layer):
    def __init__(self, name=None):
        super(LogisticEndpoint, self).__init__(name=name)
        self.loss_fn = keras.losses.MeanSquaredError()
        self.accuracy_fn = keras.metrics.MeanSquaredError(name="accuracy")

    def call(self, logits, targets=None, sample_weight=None):
        if targets is not None:
            # Compute the training-time loss value and add it
            # to the layer using `self.add_loss()`.
            loss = self.loss_fn(targets, logits, sample_weight)
            self.add_loss(loss)

            self.add_metric(self.accuracy_fn(targets, logits))
        return tf.nn.sigmoid(logits)


In [ ]:
inputs = keras.Input((1,), name="inputs")
logits = keras.layers.Dense(1)(inputs)
targets = keras.Input((1,), name="targets")
sample_weight = keras.Input((1,), name="sample_weight")
preds = LogisticEndpoint()(targets, logits)
model = keras.Model([inputs, targets, sample_weight], preds)


In [ ]:

data = {
    "inputs": np.random.random((1000, 1)),
    "targets": np.random.random((1000, 1)),
    "sample_weight": np.random.random((1000, 1)),
}

model.compile(keras.optimizers.Adam(1e-3))
model.fit(data, epochs=100)

Epoch 1/100
32/32 [==============================] - 0s 961us/step - loss: 0.1608 - accuracy: 0.1693
Epoch 2/100
32/32 [==============================] - 0s 941us/step - loss: 0.1682 - accuracy: 0.1643
Epoch 3/100
32/32 [==============================] - 0s 880us/step - loss: 0.1641 - accuracy: 0.1603
Epoch 4/100
32/32 [==============================] - 0s 904us/step - loss: 0.1558 - accuracy: 0.1563
Epoch 5/100
32/32 [==============================] - 0s 1ms/step - loss: 0.1592 - accuracy: 0.1526
Epoch 6/100
32/32 [==============================] - 0s 887us/step - loss: 0.1507 - accuracy: 0.1490
Epoch 7/100
32/32 [==============================] - 0s 1ms/step - loss: 0.1408 - accuracy: 0.1455
Epoch 8/100
32/32 [==============================] - 0s 861us/step - loss: 0.1359 - accuracy: 0.1420
Epoch 9/100
32/32 [==============================] - 0s 843us/step - loss: 0.1378 - accuracy: 0.1388
Epoch 10/100
32/32 [==============================] - 0s 968us/step - loss: 0.1440 - accuracy: 

In [ ]:
class LogisticEndpoint(keras.layers.Layer):
    def __init__(self, name=None):
        super(LogisticEndpoint, self).__init__(name=name)
        self.loss_fn = keras.losses.BinaryCrossentropy(from_logits=True)
        self.accuracy_fn = keras.metrics.BinaryAccuracy(name="accuracy")

    def call(self, logits, targets=None, sample_weight=None):
        if targets is not None:
            # Compute the training-time loss value and add it
            # to the layer using `self.add_loss()`.
            loss = self.loss_fn(targets, logits, sample_weight)
            self.add_loss(loss)

            self.add_metric(self.accuracy_fn(targets, logits, sample_weight))
        return tf.nn.softmax(logits)


In [ ]:
inputs = keras.Input((10,), name="inputs")
logits = keras.layers.Dense(1)(inputs)
targets = keras.Input((1,), name="targets")
sample_weight = keras.Input((1,), name="sample_weight")
preds = LogisticEndpoint()(logits, targets, sample_weight)
model = keras.Model([inputs, targets, sample_weight], preds)


In [ ]:
model.summary()

Model: "model_12"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
inputs (InputLayer)             [(None, 10)]         0                                            
__________________________________________________________________________________________________
dense_20 (Dense)                (None, 2)            22          inputs[0][0]                     
__________________________________________________________________________________________________
targets (InputLayer)            [(None, 2)]          0                                            
__________________________________________________________________________________________________
sample_weight (InputLayer)      [(None, 1)]          0                                            
___________________________________________________________________________________________

In [ ]:
data = {
    "inputs": np.random.random((1000, 10)),
    "targets": np.random.random((1000, 1)),
    "sample_weight": np.random.random((1000, 1)),
}

model.compile(keras.optimizers.Adam(1e-3))
model.fit(data, epochs=100)

Epoch 1/100
32/32 [==============================] - 0s 1ms/step - loss: 0.3844 - accuracy: 0.0000e+00
Epoch 2/100
32/32 [==============================] - 0s 1ms/step - loss: 0.3846 - accuracy: 0.0000e+00
Epoch 3/100
32/32 [==============================] - 0s 1ms/step - loss: 0.3711 - accuracy: 0.0000e+00
Epoch 4/100
32/32 [==============================] - 0s 1ms/step - loss: 0.3664 - accuracy: 0.0000e+00
Epoch 5/100
32/32 [==============================] - 0s 1ms/step - loss: 0.3534 - accuracy: 0.0000e+00
Epoch 6/100
32/32 [==============================] - 0s 1ms/step - loss: 0.3420 - accuracy: 0.0000e+00
Epoch 7/100
32/32 [==============================] - 0s 1ms/step - loss: 0.3674 - accuracy: 0.0000e+00
Epoch 8/100
32/32 [==============================] - 0s 1ms/step - loss: 0.3572 - accuracy: 0.0000e+00
Epoch 9/100
32/32 [==============================] - 0s 1ms/step - loss: 0.3571 - accuracy: 0.0000e+00
Epoch 10/100
32/32 [==============================] - 0s 1ms/step - loss:

In [ ]:
model.layers[1]

In [ ]:
a = tf.keras.Model(inputs=model.input, outputs=model.layers[1].output)
a(data)

<tf.Tensor: shape=(1000, 1), dtype=float32, numpy=
array([[ 3.18941981e-01],
       [ 7.30362758e-02],
       [-3.11989009e-01],
       [-1.06238522e-01],
       [ 4.10580188e-01],
       [-1.10065810e-01],
       [ 1.64381489e-01],
       [-4.60858136e-01],
       [-7.02913046e-01],
       [ 3.61756295e-01],
       [-6.50468946e-01],
       [ 8.36551070e-01],
       [-2.31277660e-01],
       [ 5.15351668e-02],
       [-3.44308197e-01],
       [-2.10618690e-01],
       [ 6.36097848e-01],
       [-6.64562345e-01],
       [ 8.49035263e-01],
       [ 1.01331758e+00],
       [ 1.87561646e-01],
       [ 4.78123352e-02],
       [-8.00531268e-01],
       [-7.68187717e-02],
       [-1.58287302e-01],
       [-3.32725316e-01],
       [-1.10167940e-03],
       [ 2.81489901e-02],
       [-6.79030195e-02],
       [-3.27961624e-01],
       [ 1.64164126e-01],
       [ 1.27809942e-01],
       [ 9.52576473e-02],
       [ 1.03629097e-01],
       [ 2.78735071e-01],
       [ 4.88448262e-01],
       [ 4.78

In [ ]:
inputs = keras.Input((764,), name="inputs")
logits = keras.layers.Dense(1)(inputs)
preds = LogisticEndpoint()(logits, targets=None, sample_weight=None)
inference_model = keras.Model(inputs, preds)

inference_model.set_weights(model.get_weights())

preds = inference_model.predict(np.random.random((1000, 764)))

In [ ]:
preds

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [ ]:
class LogReg(keras.Model):
    def __init__(self):
        super(LogReg, self).__init__()
        self.dense = keras.layers.Dense(1)
        self.logistic_endpoint = LogisticEndpoint()

    def call(self, inputs):
        # Note that all inputs should be in the first argument
        # since we want to be able to call `model.fit(inputs)`.
        logits = self.dense(inputs["inputs"])
        preds = self.logistic_endpoint(
            logits=logits,
            targets=inputs["targets"],
            sample_weight=inputs["sample_weight"],
        )
        return preds


model = LogReg()
data = {
    "inputs": np.random.random((1000, 764)),
    "targets": np.random.random((1000, 1)),
    "sample_weight": np.random.random((1000, 1)),
}

model.compile(keras.optimizers.Adam(1e-3))
model.fit(data, epochs=2)

Epoch 1/2
32/32 [==============================] - 1s 3ms/step - loss: 0.3527 - accuracy: 0.0000e+00
Epoch 2/2
32/32 [==============================] - 0s 3ms/step - loss: 0.3448 - accuracy: 0.0000e+00
